# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TeamHome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeamHome

  pod "Apollo"
  pod 'Lock', '~> 2.0'
  pod 'Auth0', '~> 1.0'
  pod 'Cloudinary', '~> 2.0'
  pod 'JWTDecode', '~> 2.2'

end
