# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TeamHome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TeamHome

  pod "Apollo"
  pod 'Auth0', '~> 1.0'
  pod 'Cloudinary', '~> 2.0'
  pod 'Material', '~> 2.16'
  pod "CSStickyHeaderFlowLayout"
  pod 'GrowingTextView', '0.6.1'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'MEVHorizontalContacts'
  pod 'Toucan', '~> 1.1'
  pod 'TagListView', '~> 1.0'

end
